### ISSUE TITLE
运行出错了??

### ISSUE THREAD

**Issue by yanwen** [dj940212/hongbao-bot#3]
module.js:559
    throw err;
    ^

Error: Cannot find module 'wechaty'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yn/hongbao-bot/app.js:1:96)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

**Comment by dj940212** [comment]
这不是缺少依赖吗

**Comment by dj940212** [comment]
npm i

**Comment by yanwen** [comment]
哦  好了 太 谢谢 哈哈
